package com.vyaparai.app;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.Signature;
import android.net.Uri;
import android.os.Build;
import android.provider.Settings;
import android.webkit.WebView;
import androidx.core.content.FileProvider;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;

/** Secure GitHub updater for sideloaded Vyapar AI builds. */
final class UpdateManager {
  static final String UPDATE_MANIFEST_URL="https://raw.githubusercontent.com/artishoepalace-oss/Vyapar-AI-Fronted-/main/update.json";
  private static final long MAX=250L*1024L*1024L;
  private final Activity activity; private WebView web; private final ExecutorService io=Executors.newSingleThreadExecutor();
  private volatile File pending; private volatile boolean waiting,dead;
  UpdateManager(Activity a,WebView w){activity=a;web=w;}
  void checkForUpdate(boolean manual){if(dead)return;io.execute(()->{try{JSONObject m=fetchManifest();JSONObject r=validate(m);r.put("manual",manual);js("onNativeInfo",r.toString());}catch(Exception e){error("Update check failed. Check your internet connection and try again.",manual);}});}
  void downloadAndInstall(String raw){if(dead)return;io.execute(()->{File part=null;try{JSONObject m=validate(new JSONObject(raw==null?"{}":raw));long target=m.optLong("versionCode");if(target<=currentCode())throw new SecurityException("The requested update is not newer than this app.");String url=m.optString("apkUrl"),expected=m.optString("sha256").toLowerCase(Locale.US);if(!expected.matches("^[a-f0-9]{64}$"))throw new SecurityException("Update checksum is invalid.");validateInitialUrl(url);File dir=new File(activity.getFilesDir(),"updates");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Update storage unavailable");part=new File(dir,"VyaparAI-update.part");File apk=new File(dir,"VyaparAI-"+safe(m.optString("versionName"))+".apk");download(url,part);if(!expected.equals(sha(part)))throw new SecurityException("Downloaded APK checksum does not match the approved release.");if(apk.exists())apk.delete();if(!part.renameTo(apk)){copy(part,apk);part.delete();}verifyApk(apk,target);progress(100,apk.length(),apk.length(),"verified");requestInstall(apk);}catch(SecurityException e){if(part!=null)part.delete();error(e.getMessage(),true);}catch(Exception e){if(part!=null)part.delete();error("Update could not be downloaded or installed. Please try again.",true);}});}
  void onResume(){if(!dead&&waiting&&pending!=null&&canInstall()){waiting=false;File f=pending;pending=null;activity.runOnUiThread(()->openInstaller(f));}}
  void destroy(){dead=true;io.shutdownNow();web=null;pending=null;}
  private JSONObject fetchManifest()throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(UPDATE_MANIFEST_URL+"?t="+System.currentTimeMillis()).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");try{if(c.getResponseCode()/100!=2)throw new IOException("HTTP "+c.getResponseCode());return new JSONObject(new String(read(c.getInputStream(),1024*1024),java.nio.charset.StandardCharsets.UTF_8));}finally{c.disconnect();}}
  private JSONObject validate(JSONObject in)throws Exception{String id=in.optString("appId",activity.getPackageName());if(!activity.getPackageName().equals(id))throw new SecurityException("Update package does not match Vyapar AI.");boolean enabled=in.optBoolean("enabled",true);long code=in.optLong("versionCode");String name=in.optString("versionName");String url=in.optString("apkUrl");String hash=in.optString("sha256").toLowerCase(Locale.US);if(enabled&&(code<=0||name.isEmpty()))throw new SecurityException("Update metadata is incomplete.");if(!url.isEmpty())validateInitialUrl(url);if(!hash.isEmpty()&&!hash.matches("^[a-f0-9]{64}$"))throw new SecurityException("Update checksum format is invalid.");long cur=currentCode(),min=in.optLong("minimumSupportedVersionCode",0);boolean available=enabled&&code>cur,force=available&&(in.optBoolean("mandatory",false)||cur<min);JSONObject o=new JSONObject(in.toString());o.put("currentVersionCode",cur);o.put("currentVersionName",currentName());o.put("updateAvailable",available);o.put("force",force);o.put("installPermissionGranted",canInstall());return o;}
  private void download(String address,File out)throws Exception{String next=address;for(int redirects=0;redirects<6;redirects++){URL u=new URL(next);if(!"https".equalsIgnoreCase(u.getProtocol()))throw new SecurityException("HTTPS required.");String host=u.getHost().toLowerCase(Locale.US);if(redirects==0)validateInitialUrl(next);else if(!(host.equals("github.com")||host.endsWith("githubusercontent.com")))throw new SecurityException("Unapproved update redirect.");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","VyaparAI-Android-Updater");int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new IOException("Bad redirect");next=new URL(u,loc).toString();continue;}if(code/100!=2){c.disconnect();throw new IOException("HTTP "+code);}long total=c.getContentLengthLong();if(total>MAX){c.disconnect();throw new IOException("APK too large");}try(InputStream in=new BufferedInputStream(c.getInputStream());FileOutputStream fos=new FileOutputStream(out)){byte[] b=new byte[65536];long done=0;int n;while((n=in.read(b))!=-1){done+=n;if(done>MAX)throw new IOException("APK too large");fos.write(b,0,n);progress(total>0?(int)Math.min(99,done*100/total):-1,done,total,"downloading");}}finally{c.disconnect();}return;}throw new IOException("Too many redirects");}
  private void verifyApk(File apk,long expected)throws Exception{PackageManager pm=activity.getPackageManager();int flags=Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageInfo d=pm.getPackageArchiveInfo(apk.getAbsolutePath(),flags);if(d==null||!activity.getPackageName().equals(d.packageName))throw new SecurityException("Downloaded file is not a valid Vyapar AI APK.");long dc=Build.VERSION.SDK_INT>=28?d.getLongVersionCode():d.versionCode;if(dc!=expected||dc<=currentCode())throw new SecurityException("Downloaded APK version does not match the approved update.");PackageInfo cur=pm.getPackageInfo(activity.getPackageName(),flags);if(!signers(cur).equals(signers(d))||signers(cur).isEmpty())throw new SecurityException("Update signing certificate does not match this installed app. Install the permanently signed Vyapar AI build manually once; later updates can install in place.");}
  private Set<String> signers(PackageInfo p)throws Exception{Set<String>s=new HashSet<>();Signature[] a;if(Build.VERSION.SDK_INT>=28){if(p.signingInfo==null)return s;a=p.signingInfo.hasMultipleSigners()?p.signingInfo.getApkContentsSigners():p.signingInfo.getSigningCertificateHistory();}else a=p.signatures;if(a!=null)for(Signature x:a)s.add(hex(MessageDigest.getInstance("SHA-256").digest(x.toByteArray())));return s;}
  private void requestInstall(File apk){pending=apk;activity.runOnUiThread(()->{if(Build.VERSION.SDK_INT>=26&&!activity.getPackageManager().canRequestPackageInstalls()){waiting=true;js("onInstallPermissionRequired",null);try{activity.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+activity.getPackageName())));}catch(Exception e){waiting=false;error("Allow installation from this source in Android settings, then try again.",true);}return;}File f=pending;pending=null;openInstaller(f);});}
  private void openInstaller(File apk){try{Uri u=FileProvider.getUriForFile(activity,activity.getPackageName()+".updateprovider",apk);Intent i=new Intent(Intent.ACTION_INSTALL_PACKAGE,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);activity.startActivity(i);js("onInstallerOpened",null);}catch(Exception e){error("Android installer could not be opened for this update.",true);}}
  private boolean canInstall(){return Build.VERSION.SDK_INT<26||activity.getPackageManager().canRequestPackageInstalls();}
  private long currentCode(){try{PackageInfo p=activity.getPackageManager().getPackageInfo(activity.getPackageName(),0);return Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode;}catch(Exception e){return 0;}}
  private String currentName(){try{return activity.getPackageManager().getPackageInfo(activity.getPackageName(),0).versionName;}catch(Exception e){return"";}}
  private void validateInitialUrl(String s)throws Exception{URL u=new URL(s);if(!"https".equalsIgnoreCase(u.getProtocol())||!"github.com".equalsIgnoreCase(u.getHost())||!u.getPath().startsWith("/artishoepalace-oss/Vyapar-AI-Fronted-/releases/download/"))throw new SecurityException("Update APK must come from the approved GitHub release.");}
  private static byte[] read(InputStream in,int max)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n,total=0;while((n=in.read(b))!=-1){total+=n;if(total>max)throw new IOException("Response too large");o.write(b,0,n);}return o.toByteArray();}
  private static String sha(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[]b=new byte[65536];int n;while((n=in.read(b))!=-1)d.update(b,0,n);}return hex(d.digest());}
  private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}
  private static void copy(File a,File b)throws Exception{try(InputStream i=new FileInputStream(a);OutputStream o=new FileOutputStream(b)){byte[]x=new byte[65536];int n;while((n=i.read(x))!=-1)o.write(x,0,n);}}
  private static String safe(String s){s=s==null?"update":s.replaceAll("[^A-Za-z0-9._-]","");return s.isEmpty()?"update":s;}
  private void progress(int pct,long bytes,long total,String phase){try{JSONObject o=new JSONObject();o.put("percent",pct);o.put("bytes",bytes);o.put("total",total);o.put("phase",phase);js("onNativeProgress",o.toString());}catch(Exception ignored){}}
  private void error(String msg,boolean visible){try{JSONObject o=new JSONObject();o.put("message",msg==null?"Update failed.":msg);o.put("visible",visible);js("onNativeError",o.toString());}catch(Exception ignored){}}
  private void js(String fn,String arg){WebView w=web;if(dead||w==null)return;String code="window.VyaparGitHubUpdater&&window.VyaparGitHubUpdater."+fn+"("+(arg==null?"":arg)+");";w.post(()->{if(!dead&&web!=null)web.evaluateJavascript(code,null);});}
}
